OnlineShop/Areas/Admin/Controllers/ProductTypesController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Data;
using OnlineShop.Models;

namespace OnlineShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductTypesController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ProductTypesController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var data = _db.ProductTypes.ToList();
            return View(data);
        }

        //Get Method Product Types Create
        public IActionResult Create()
        {
            return View();
        }
        //Post Method Product Types
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductTypes model)
        {
            if (ModelState.IsValid)
            {
                _db.ProductTypes.Add(model);
                await _db.SaveChangesAsync();
                TempData["Save"] = "Product save successfully";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(model);
            }
        }

        //Get Method Product Types Edit
        public IActionResult Edit(int? id)
        {
            if (id==null)
            {
                return NotFound();
            }
            var ProductType = _db.ProductTypes.FirstOrDefault(e=> e.Id == id); 
            if (ProductType==null)
            {
                return NotFound();
            }
            return View(ProductType);
        }
        //Post Method Edit 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProductTypes model)
        {
            if (ModelState.IsValid)
            {
                _db.ProductTypes.Update(model);
                await _db.SaveChangesAsync();
                TempData["update"] = "product updated";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(model);
            }
        }

        //Get Method Product Types Details
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var ProductType = _db.ProductTypes.FirstOrDefault(e => e.Id == id);
            if (ProductType == null)
            {
                return NotFound();
            }
            return View(ProductType);
        }
        //Post Method Details 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  IActionResult Details(ProductTypes model)
        {
            return RedirectToAction(nameof(Index));
        }


        //Delete Product Types
        public IActionResult Delete(int? id, ProductTypes model)
        {
            if (id == null)
            {
                return NotFound();
            }
            if(id != model.Id)
            {

            }
            var ProductType = _db.ProductTypes.FirstOrDefault(e => e.Id == id);
            if (ProductType == null)
            {
                return NotFound();
            }
            return View(ProductType);
        }

        //Post Method Delete 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(ProductTypes model)
        {
            if (ModelState.IsValid)
            {
                _db.ProductTypes.Remove(model);
                await _db.SaveChangesAsync();
                TempData["delete"] = "Product deleted";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(model);
            }
        }

    }
}

OnlineShop/Areas/Admin/Controllers/SpecialTagController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Data;
using OnlineShop.Models;

namespace OnlineShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SpecialTagController : Controller
    {
        private readonly ApplicationDbContext _db;
        public SpecialTagController(ApplicationDbContext db)
        {
            _db= db;
        }
        public IActionResult Index()
        {
            var data = _db.SpecialTages.ToList();
            return View(data);
        }
        // Create in Get
        public IActionResult Create()
        {
            return View();
        }
        //Create in Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SpecialTag model)
        {
            if (ModelState.IsValid)
            {
                _db.SpecialTages.Add(model);
                await _db.SaveChangesAsync();   
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(model);
            }
        }

        //Post Edit
        public IActionResult Edit(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var specialtag = _db.SpecialTages.FirstOrDefault(e=>e.Id == id);
            if (specialtag == null)
            {
                return NotFound();
            }
            return View(specialtag);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(SpecialTag model)
        {
            if (ModelState.IsValid)
            {
                _db.SpecialTages.Update(model);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(model);
            }
        }
        //Get Method Special tag Details
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var specialtag = _db.SpecialTages.FirstOrDefault(e => e.Id == id);
            if (specialtag == null)
            {
                return NotFound();
            }
            return View(specialtag);
        }
        //Post Method Details 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details(SpecialTag model)
        {
            return RedirectToAction(nameof(Index));
        }


        //Delete Product Types
        public IActionResult Delete(int? id, SpecialTag model)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (id != model.Id)
            {

            }
            var specialtag = _db.SpecialTages.FirstOrDefault(e => e.Id == id);
            if (specialtag == null)
            {
                return NotFound();
            }
            return View(specialtag);
        }

        //Post Method Delete 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(SpecialTag model)
        {
            if (ModelState.IsValid)
            {
                _db.SpecialTages.Remove(model);
                await _db.SaveChangesAsync();
                TempData["delete"] = "Product deleted";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(model);
            }
        }
    }
}

OnlineShop/Views/Shared/_ButtonPartial.cshtml
@model int
@{
    ViewData["Title"] = "_ButtonPartial";
}


<td style="width:150px">
    <div class="btn-group">
        <a asp-action="Edit" asp-controller="ProductTypes" class="btn btn-primary" asp-route-id="@Model"><i class="fa-solid fa-pen-to-square"></i></a>
        <a asp-action="Details" asp-controller="ProductTypes" class="btn btn-info" asp-route-id="@Model"><i class="fa-solid fa-list"></i></a>
        <a asp-action="Delete" asp-controller="ProductTypes" class="btn btn-danger" asp-route-id="@Model"><i class="fa-sharp fa-solid fa-trash"></i></a>
    </div>
</td>

OnlineShop/Views/Shared/_ButtonPartialtag.cshtml
@model int
@{
    ViewData["Title"] = "_ButtonPartialtag";
}


<td style="width:150px">
    <div class="btn-group">
        <a asp-action="Edit" asp-controller="SpecialTag" class="btn btn-primary" asp-route-id="@Model"><i class="fa-solid fa-pen-to-square"></i></a>
        <a asp-action="Details" asp-controller="SpecialTag" class="btn btn-info" asp-route-id="@Model"><i class="fa-solid fa-list"></i></a>
        <a asp-action="Delete" asp-controller="SpecialTag" class="btn btn-danger" asp-route-id="@Model"><i class="fa-sharp fa-solid fa-trash"></i></a>
    </div>
</td>

OnlineShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineShop</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" 
    integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlineShop.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnlineShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="ProductTypes" asp-action="Index">ProductType</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="SpecialTag" asp-action="Index">SpecialTage</a>
                        </li>
                        

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - OnlineShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>